### ISSUE TITLE
payload is not boolean

### ISSUE THREAD

**Issue by RehDen** [redplc/node-red-contrib-redplc#1]
Hello.
I am trying to use your beautiful creation.
There are incomprehensible problems ...
`[{"id":"301905df.94f3da","type":"tab","label":"PLC","disabled":false,"info":""},{"id":"2386ab76.07bb44","type":"redplc-cpu","z":"301905df.94f3da","sdelay":200,"tinput":"100","toutput":"100","trungs":"100","outputs":2,"stime":false,"x":130,"y":180,"wires":[["64663565.8cb3ac"],[]]},{"id":"bcd161ba.c8471","type":"coil","z":"301905df.94f3da","operation":"store","operand":"M","address":0,"bit":"1","counter":"R","flipflop":"S","name":"","x":750,"y":180,"wires":[[]]},{"id":"23950b72.310f44","type":"inject","z":"301905df.94f3da","name":"","props":[{"p":"payload"}],"repeat":"0.1","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":190,"y":440,"wires":[["e310e3e2.5fe3d"]]},{"id":"e310e3e2.5fe3d","type":"coil","z":"301905df.94f3da","operation":"store","operand":"M","address":0,"bit":"2","counter":"R","flipflop":"S","name":"","x":440,"y":460,"wires":[[]]},{"id":"e0e1188c.77e618","type":"inject","z":"301905df.94f3da","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"false","payloadType":"bool","x":190,"y":480,"wires":[["e310e3e2.5fe3d"]]},{"id":"303a28f5.f9de68","type":"contact","z":"301905df.94f3da","operation":"read","operand":"M","address":0,"bit":"2","counter":"QU","timer":"Q","flipflop":"R","name":"","x":530,"y":180,"wires":[["bcd161ba.c8471"]]},{"id":"64663565.8cb3ac","type":"rung-start","z":"301905df.94f3da","comment":"","x":330,"y":180,"wires":[["303a28f5.f9de68"]]}]`

> ![Безымянный](https://user-images.githubusercontent.com/56017912/113299325-6e533b00-9305-11eb-9e2a-60d46406af36.jpg)

What could be wrong? What am I doing wrong?
Where can I find more detailed instructions?

**Comment by redplc** [comment]
Hi,
The first output sends "input" or "output" string msg.payload messages.
With this messages the hardware nodes updates input or output (i.e gpio).
The second output sends boolean true message.
Please connect the nodes to the second output.
You can add more outputs with change the output property in cpu-node.
Ocean (Derya)

**Comment by RehDen** [comment]
Thanks!
As always .... First we do .. then we read the instructions =)
To make the element work, I had to delete it and then add it again. If you give it a string signal once, it stops working ...
